import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <div
          style={{
            padding: "10px 16px 14px",
            textAlign: "center",
            background: "#111827",
            color: "#9ca3af",
            fontSize: "11px",
          }}
        >
          Built by{" "}
          <a
            href="https://www.myapptly.com/"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: "#facc15", fontWeight: 700, textDecoration: "none" }}
          >
            APPTLY
          </a>
        </div>
      </body>
    </html>
  );
}
